-- AI Integration Migration: embeddings moved off personal Google AI key
-- (gemini-embedding-001, 768 dims) to a COSET-owned OpenAI-compatible
-- embeddings provider configured via AI_EMBEDDINGS_* env vars.
--
-- Default dimension: 1024 (jina-embeddings-v3, mistral-embed, Cohere
-- embed-english-v3, bge-m3, qwen3-embedding-0.6b are all 1024). If the
-- allocated embedding model has a different native dimension, change BOTH
-- the vector type below and the function signature, and set AI_EMBEDDINGS_DIM
-- to match BEFORE running the reembed backfill.
--
-- Existing rows are deleted: they were generated by the old model and are
-- fully replaced by scripts/reembed-reports.ts. Run the backfill right after
-- this migration; until it completes, semantic search degrades to the built-in
-- PostgreSQL full-text search fallback.

-- Drop the HNSW index first — it must be rebuilt for the new dimension anyway
-- and ALTER TYPE fails while an index depends on the column.
DROP INDEX IF EXISTS public.report_embeddings_embedding_idx;

-- Old vectors are invalid under the new model; the backfill repopulates.
DELETE FROM public.report_embeddings;

ALTER TABLE public.report_embeddings
    ALTER COLUMN embedding TYPE vector(1024);

CREATE INDEX report_embeddings_embedding_idx
    ON public.report_embeddings USING hnsw (embedding vector_cosine_ops);

DROP FUNCTION IF EXISTS public.match_report_embeddings(vector(768), float, int, uuid);

CREATE OR REPLACE FUNCTION public.match_report_embeddings(
  query_embedding vector(1024),
  match_threshold float,
  match_count int,
  filter_report_id uuid DEFAULT NULL
)
RETURNS TABLE (
  id uuid,
  report_id uuid,
  content text,
  similarity float
)
LANGUAGE plpgsql STABLE
AS $$
BEGIN
  RETURN QUERY
  SELECT
    report_embeddings.id,
    report_embeddings.report_id,
    report_embeddings.content,
    1 - (report_embeddings.embedding <=> query_embedding) AS similarity
  FROM report_embeddings
  WHERE (filter_report_id IS NULL OR report_embeddings.report_id = filter_report_id)
    AND 1 - (report_embeddings.embedding <=> query_embedding) > match_threshold
  ORDER BY (report_embeddings.embedding <=> query_embedding) ASC
  LIMIT match_count;
END;
$$;
